name: Deploy to GitHub Pages

# déclenche l'action manuellement après un push sur la branch main
on:
  workflow_dispatch:
    branches:
      - main

# définition des permissions et autorisation de permettre le déploiement sur GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# autorise un déploiement à la fois
concurrency:
  group: 'pages'
  cancel-in-progress: true

# définition des étapes d'intégration et de déploiement
jobs:
  # Etape d'intégration
  build:
    environment: production
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      # Récupération du code du projet
      - name: Fetch code
        uses: actions/checkout@v4

      # Installation des dépendances
      - name: Install dependencies
        run: npm install

      # Build du projet (transpilation ts -> js, scss -> css)
      - name: Build
        run: npm run build

      # Upload artefact vers GitHub Pages 
      - name: Upload artifact to github pages
        uses: actions/upload-pages-artifact@v2
        with:
          name: artifact
          path: ./dist
      
  # Etape de déploiement
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # Configuration de GitHub Pages
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3
      
      # Déploiement sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          artifact_name: artifact